version: '3'

services:
  devcontainer:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../:/workspaces/devcontainer-bug
      - /workspaces/devcontainer-bug/node_modules
    # Overrides default command so things don't shut down after the process ends.
    entrypoint: /usr/local/share/docker-init.sh
    command: sleep infinity

  app:
    build:
      context: ../
      dockerfile: Dockerfile
    volumes:
      - ../:/root/devcontainer-bug
      - /root/devcontainer-bug/node_modules
    ports:
      - 3000:3000
      - 4000:4000
